GET  http://localhost:4000/



###
POST http://localhost:4000/addNewTask
Content-Type: application/json

{
    "title": "Meeting"    

}

### get all tasks
GET http://localhost:4000/allTasks


### Get single task 
GET http://localhost:4000/viewDetails/61141fc8ded0b717ac7b157a